### PR TITLE
enable dl/compile caching using build mounts

### PR DESCRIPTION
**Pull request by jakogut**
Change-type: minor
Signed-off-by: Joseph Kogut <joseph@balena.io>

### CODE REVIEW

**Comment by klutchell** [comment]
When using `docker buildx` the cache dir doesn't seem to get created by `--mount=type=cache,target=/cache/,uid=1000,gid=1000` so the buildroot compile fails.

**Comment by jakogut** [comment]
> When using `docker buildx` the cache dir doesn't seem to get created by `--mount=type=cache,target=/cache/,uid=1000,gid=1000` so the buildroot compile fails.

I experienced the same behavior after testing. This is odd. The docs explicitly say `docker buildx` always enables BuildKit, and the appropriate dockerfile frontend should be enabled.

https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md#run---mounttypecache

**Comment by klutchell** [comment]
Setting the shared mode to private seems to have fixed the buildx compile. Can you verify the cache is still being used correctly?

**Review by klutchell — APPROVED** [review]
lgtm

**Pull request merged**
